#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ZRF Science Fair 2026 - Project Summary PDF (body, no cover)
Bangla Publishing Studio - Topu Biswas, University of Rajshahi
Numbering plan (mandatory):
| Outline Index | Type    | Chapter # | Title                    |
|---------------|---------|-----------|--------------------------|
| 1             | cover   | -         | Cover (separate PDF)     |
| 2             | content | -         | Project Identification   |
| 3             | content | 1         | Project Abstract         |
| 4             | content | 2         | Objectives               |
| 5             | content | 3         | Innovation / Novelty     |
| 6             | content | 4         | Expected Impact          |
| 7             | content | 5         | Technical Overview       |
| 8             | content | 6         | Current Status & Roadmap |
"""
import os
import sys

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether, CondPageBreak,
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ------------------------------------------------------------------
# Font registration (allowed fonts only)
# ------------------------------------------------------------------
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))

registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')

# Mandatory automatic font fallback for mixed-script safety
sys.path.insert(0, '/home/z/my-project/skills/pdf/scripts')
from pdf import install_font_fallback  # noqa: E402
install_font_fallback()

# ------------------------------------------------------------------
# Cascade Palette (auto-generated by design_engine.py palette-cascade)
# ------------------------------------------------------------------
from reportlab.lib import colors  # noqa: E402

PAGE_BG       = colors.HexColor('#f4f5f5')
SECTION_BG    = colors.HexColor('#f0f1f2')
CARD_BG       = colors.HexColor('#e8eaeb')
TABLE_STRIPE  = colors.HexColor('#ebeded')
HEADER_FILL   = colors.HexColor('#32454e')
COVER_BLOCK   = colors.HexColor('#566a74')
BORDER        = colors.HexColor('#acbdc5')
ICON          = colors.HexColor('#4b86a4')
ACCENT        = colors.HexColor('#1f6c92')
ACCENT_2      = colors.HexColor('#c23a50')
TEXT_PRIMARY  = colors.HexColor('#131515')
TEXT_MUTED    = colors.HexColor('#747b7e')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ------------------------------------------------------------------
# Document setup
# ------------------------------------------------------------------
OUT = '/home/z/my-project/zrf-submission/body.pdf'
DOC_TITLE = 'Bangla Publishing Studio - ZRF Science Fair 2026 Project Summary'

LM = RM = 2.0 * cm            # symmetric margins (mandatory)
TM = 2.4 * cm
BM = 2.2 * cm
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - LM - RM

doc = SimpleDocTemplate(
    OUT, pagesize=A4,
    leftMargin=LM, rightMargin=RM, topMargin=TM, bottomMargin=BM,
    title=DOC_TITLE,
    author='Topu Biswas',
    creator='Z.ai',
    subject='Project Summary for ZRF Science Fair 2026 Registration',
)

# ------------------------------------------------------------------
# Styles
# ------------------------------------------------------------------
h1 = ParagraphStyle(
    name='H1', fontName='FreeSerif', fontSize=16, leading=21,
    textColor=HEADER_FILL, spaceBefore=18, spaceAfter=4,
)
body = ParagraphStyle(
    name='Body', fontName='FreeSerif', fontSize=10.5, leading=17,
    textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceBefore=0, spaceAfter=8,
)
bullet = ParagraphStyle(
    name='Bullet', fontName='FreeSerif', fontSize=10.5, leading=17,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    leftIndent=16, bulletIndent=4, spaceAfter=6,
)
numbered = ParagraphStyle(
    name='Numbered', fontName='FreeSerif', fontSize=10.5, leading=17,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    leftIndent=20, bulletIndent=2, spaceAfter=7,
)
lead = ParagraphStyle(
    name='Lead', fontName='FreeSerif', fontSize=10.5, leading=17,
    textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=8,
)
th_style = ParagraphStyle(
    name='TH', fontName='FreeSerif', fontSize=10, leading=13,
    textColor=colors.white, alignment=TA_LEFT,
)
td_label = ParagraphStyle(
    name='TDLabel', fontName='FreeSerif', fontSize=9.5, leading=13,
    textColor=TEXT_MUTED, alignment=TA_LEFT,
)
td_value = ParagraphStyle(
    name='TDValue', fontName='FreeSerif', fontSize=9.5, leading=13,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
)
stat_big = ParagraphStyle(
    name='StatBig', fontName='FreeSerif', fontSize=15, leading=19,
    textColor=ACCENT, alignment=TA_CENTER,
)
stat_label = ParagraphStyle(
    name='StatLabel', fontName='FreeSerif', fontSize=8, leading=11,
    textColor=TEXT_MUTED, alignment=TA_CENTER,
)
caption = ParagraphStyle(
    name='Caption', fontName='FreeSerif', fontSize=8.5, leading=12,
    textColor=TEXT_MUTED, alignment=TA_CENTER, spaceBefore=3, spaceAfter=6,
)

MAX_KEEP_HEIGHT = PAGE_H * 0.4


def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        w, h = el.wrap(AVAIL_W, PAGE_H)
        total_h += h
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)


def heading(text):
    """H1 heading + accent underline rule, kept together with the rule."""
    p = Paragraph(f'<b>{text}</b>', h1)
    rule = HRFlowable(width='100%', thickness=1.4, color=ACCENT,
                      spaceBefore=0, spaceAfter=10)
    return [CondPageBreak(PAGE_H * 0.25)] + safe_keep_together([p, rule])


# ------------------------------------------------------------------
# Header / footer
# ------------------------------------------------------------------
def on_page(canvas, doc_):
    canvas.saveState()
    # Header
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LM, PAGE_H - 1.35 * cm, 'BANGLA PUBLISHING STUDIO')
    canvas.drawRightString(PAGE_W - RM, PAGE_H - 1.35 * cm, 'ZRF SCIENCE FAIR 2026')
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(LM, PAGE_H - 1.55 * cm, PAGE_W - RM, PAGE_H - 1.55 * cm)
    # Footer
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.6)
    canvas.line(LM, 1.55 * cm, PAGE_W - RM, 1.55 * cm)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LM, 1.15 * cm, 'Topu Biswas  |  Department of ICE, University of Rajshahi')
    canvas.drawRightString(PAGE_W - RM, 1.15 * cm, f'Page {doc_.page}')
    canvas.restoreState()


# ------------------------------------------------------------------
# Content
# ------------------------------------------------------------------
story = []

# ---- Project Identification (unnumbered) ----
story += heading('Project Identification')

ident_rows = [
    ('Project Title', 'Bangla Publishing Studio - A Free, Offline-Ready Web Platform for '
                      'MS-Word-Like Bengali Book Typesetting with Print-Press Imposition'),
    ('Scientific Field', 'Engineering & Innovation'),
    ('Project Type', 'Individual Project'),
    ('Participant', 'Topu Biswas'),
    ('Current Class / Year', 'B.Sc. (Engg.) 2nd Year'),
    ('Institution', 'Department of Information and Communication Engineering (ICE), University of Rajshahi'),
    ('Division / District', 'Rajshahi / Rajshahi'),
    ('Age Group', 'Group C (18 years or above)'),
    ('Event', 'ZRF Science Fair 2026 - Ziaur Rahman Foundation'),
]

ident_data = []
for label, value in ident_rows:
    ident_data.append([
        Paragraph(f'<b>{label}</b>', td_label),
        Paragraph(value, td_value),
    ])

col_widths = [0.28 * AVAIL_W, 0.72 * AVAIL_W]
assert sum(col_widths) <= AVAIL_W + 0.5
ident_table = Table(ident_data, colWidths=col_widths, hAlign='CENTER')
ident_style = [
    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('LEFTPADDING', (0, 0), (-1, -1), 10),
    ('RIGHTPADDING', (0, 0), (-1, -1), 10),
    ('LINEBELOW', (0, 0), (-1, -2), 0.5, BORDER),
    ('LINEBELOW', (0, -1), (-1, -1), 0.9, HEADER_FILL),
    ('LINEABOVE', (0, 0), (-1, 0), 0.9, HEADER_FILL),
]
for i in range(len(ident_data)):
    if i % 2 == 1:
        ident_style.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_ODD))
ident_table.setStyle(TableStyle(ident_style))
story.append(ident_table)
story.append(Spacer(1, 18))

# ---- Key figures callout ----
callout_data = [[
    Table([[Paragraph('<b>5</b>', stat_big)], [Paragraph('Paper sizes incl. Demy & Crown', stat_label)]], colWidths=[0.23 * AVAIL_W]),
    Table([[Paragraph('<b>1-Click</b>', stat_big)], [Paragraph('Farma (imposition) PDF for press', stat_label)]], colWidths=[0.23 * AVAIL_W]),
    Table([[Paragraph('<b>100%</b>', stat_big)], [Paragraph('Free, zero installation', stat_label)]], colWidths=[0.23 * AVAIL_W]),
    Table([[Paragraph('<b>Offline</b>', stat_big)], [Paragraph('PWA autosave, no internet needed', stat_label)]], colWidths=[0.23 * AVAIL_W]),
]]
callout = Table(callout_data, colWidths=[0.25 * AVAIL_W] * 4, hAlign='CENTER')
callout.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
    ('BOX', (0, 0), (-1, -1), 0.8, ACCENT),
    ('INNERGRID', (0, 0), (-1, -1), 0.5, BORDER),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('TOPPADDING', (0, 0), (-1, -1), 10),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
]))
for inner in callout_data[0]:
    inner.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
story.append(callout)
story.append(Spacer(1, 6))
story.append(Paragraph('Key capabilities of Bangla Publishing Studio at a glance.', caption))
story.append(Spacer(1, 10))

# ---- 1. Project Abstract ----
story += heading('1. Project Abstract')
story.append(Paragraph(
    'Publishing a book in Bangladesh still depends on expensive desktop-publishing software, '
    'scarce and costly typesetting operators, and repeated proof prints at the press. For teachers, '
    'coaching centres, rural writers, and small publishers, these barriers make book production slow, '
    'risky, and expensive. <b>Bangla Publishing Studio</b> removes these barriers with a free, '
    'zero-installation web platform that works as simply as Microsoft Word but produces real, '
    'print-ready books in Bengali.', lead))
story.append(Paragraph(
    'Running entirely in the browser, the platform offers true paginated book layout on standard '
    'physical paper sizes (A4, Letter, Legal, Demy, and Crown), native Bengali fonts (Kalpurush, '
    'SolaimanLipi, Siyam Rupali), and rich WYSIWYG editing with tables, images, text boxes, shapes, '
    'icons, and page headers and footers. Progressive Web App technology keeps the editor fully '
    'usable without internet, and an automatic IndexedDB autosave protects every keystroke. Its most '
    'distinctive capability is <b>Farma</b> generation: the industry-standard imposition scheme used '
    'by Bangladeshi printing presses, in which book pages are rearranged into printer\u2019s signatures '
    'for offset printing. With one click, the same document can be exported as a press-ready Farma PDF, '
    'a normal print PDF, a DOCX file, or a self-contained HTML document.', body))
story.append(Paragraph(
    'The platform is built with modern web technologies (Next.js, React, and ProseMirror) and performs '
    'all processing on the user\u2019s own device, keeping it fast, private, and free of server costs. '
    'By uniting familiar word-processing simplicity with professional print engineering, Bangla '
    'Publishing Studio aims to democratize book production for the millions of Bengali readers, '
    'writers, and educators who have been excluded from digital publishing until now.', body))

# ---- 2. Objectives ----
story += heading('2. Objectives')
objectives = [
    'To develop a free, browser-based WYSIWYG editor that feels as familiar as Microsoft Word but '
    'automatically paginates content into real book pages.',
    'To implement true print pagination on the standard physical book sizes used in Bangladesh, '
    'including A4, Letter, Legal, Demy, and Crown.',
    'To generate industry-standard <b>Farma</b> (imposition) output with signature-based page '
    'ordering and recto-verso pairing, so any local press can print directly without costly '
    'desktop-publishing software or manual page rearrangement.',
    'To guarantee offline-first reliability through PWA service workers and automatic local '
    'autosave, so unstable internet connections never destroy a writer\u2019s work.',
    'To provide one-click export from a single source file to print-ready PDF, imposed Farma PDF, '
    'DOCX, self-contained HTML, and JSON backup.',
    'To keep the entire platform completely free and accessible to students, teachers, coaching '
    'centres, writers, and small publishers everywhere in Bangladesh.',
]
for i, obj in enumerate(objectives, 1):
    story.append(Paragraph(obj, numbered, bulletText=f'{i}.'))

# ---- 3. Innovation / Novelty ----
story += heading('3. Innovation / Novelty')
story.append(Paragraph(
    'The core novelty of Bangla Publishing Studio is that it is, to the best of our knowledge, the '
    'first browser-based platform that combines three things which have never been united in one '
    'free tool: (a) MS-Word-like WYSIWYG editing, (b) true physical-size book pagination, and '
    '(c) the Farma imposition scheme of the Bangladeshi printing industry. International software '
    'such as Adobe InDesign or MS Publisher ignores both Demy/Crown paper sizes and local imposition '
    'practice, forcing Bangladeshi presses to redo layout work manually. This project speaks the '
    'exact language of the local press.', body))
for b in [
    '<b>Zero-setup architecture:</b> every processing step happens client-side (Next.js + React + '
    'ProseMirror). Nothing is installed, nothing is licensed, and nothing is sent to a server - '
    'privacy and speed are achieved by design.',
    '<b>Offline-first PWA:</b> after the first visit, the complete editor, Bengali fonts, and '
    'autosave work without any internet connection - a decisive advantage for rural users with '
    'unstable connectivity.',
    '<b>Print-industry awareness:</b> signature-based Farma sheets with correct recto-verso pairing '
    'let a press print, fold, and bind a book exactly as it does today, eliminating an entire class '
    'of manual errors.',
    '<b>Democratization of publishing:</b> the entry barrier for producing a properly typeset, '
    'press-ready book drops from thousands of taka (software licence plus operator fees) to zero.',
    '<b>Local-language engineering:</b> Bengali fonts and complex-script rendering are treated as '
    'first-class features, not an afterthought.',
]:
    story.append(Paragraph(b, bullet, bulletText='\u2022'))

# ---- 4. Expected Impact ----
story += heading('4. Expected Impact')
story.append(Paragraph(
    '<b>Educational impact.</b> Teachers and coaching centres will be able to self-produce textbooks, '
    'guides, and question banks in hours instead of weeks, and university students will gain a '
    'working example of modern web engineering - progressive web apps, offline-first storage, and '
    'browser-based print technology - that they can study, reuse, and extend for other South Asian '
    'languages.', body))
story.append(Paragraph(
    '<b>Social and economic impact.</b> Rural and low-income writers will be able to publish novels, '
    'poetry, and research without middlemen, because the platform removes software costs, operator '
    'fees, and the longest part of the pre-press cycle. Small publishers will cut typesetting costs '
    'and turnaround time, keeping more of the value of publishing inside local communities.', body))
story.append(Paragraph(
    '<b>Cultural impact.</b> By making Bengali book production as easy as typing a document, the '
    'project strengthens the creation and preservation of Bengali-language knowledge in the digital '
    'era - more textbooks, more literature, and more local history printed in the mother tongue.', body))
story.append(Paragraph(
    '<b>Scalability.</b> The architecture is deliberately open: future versions will add more '
    'imposition schemes, professional book templates, collaborative editing, and AI-assisted layout, '
    'and the same model can be adapted to other underserved languages with minimal change.', body))

# ---- 5. Technical Overview ----
story += heading('5. Technical Overview')
tech_rows = [
    ('Frontend framework', 'Next.js 16 (App Router), React 19, TypeScript 5, Tailwind CSS'),
    ('Editing engine', 'ProseMirror / TipTap with custom nodes for images, text boxes, shapes, and icons'),
    ('Pagination engine', 'Client-side true-page layout with physical paper sizes (A4, Letter, Legal, Demy, Crown)'),
    ('Imposition engine', 'Farma (signature-based) page reordering with recto-verso pairing for offset printing'),
    ('Storage', 'IndexedDB autosave via Dexie.js, plus JSON project backup and restore'),
    ('Offline support', 'Progressive Web App with service worker; installable and fully usable offline'),
    ('Export formats', 'Print PDF, Farma imposition PDF, DOCX, self-contained HTML, JSON'),
    ('Bengali typography', 'Kalpurush, SolaimanLipi, and Siyam Rupali font families with complex-script rendering'),
]
tech_data = [[Paragraph('<b>Layer</b>', th_style), Paragraph('<b>Technology</b>', th_style)]]
for label, value in tech_rows:
    tech_data.append([Paragraph(label, td_label), Paragraph(value, td_value)])
tech_widths = [0.26 * AVAIL_W, 0.74 * AVAIL_W]
assert sum(tech_widths) <= AVAIL_W + 0.5
tech_table = Table(tech_data, colWidths=tech_widths, hAlign='CENTER', repeatRows=1)
tech_style = [
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ('TOPPADDING', (0, 0), (-1, -1), 5),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ('LEFTPADDING', (0, 0), (-1, -1), 10),
    ('RIGHTPADDING', (0, 0), (-1, -1), 10),
]
for i in range(1, len(tech_data)):
    if i % 2 == 0:
        tech_style.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_ODD))
tech_table.setStyle(TableStyle(tech_style))
story.append(tech_table)
story.append(Spacer(1, 6))
story.append(Paragraph('Table 1: Technology stack of Bangla Publishing Studio.', caption))

# ---- 6. Current Status & Roadmap ----
story += heading('6. Current Status & Roadmap')
story.append(Paragraph(
    'A fully working prototype of Bangla Publishing Studio is already deployed on the public internet '
    'and is being used to create real documents. The project is version-controlled on GitHub with a '
    'clean, audited codebase, continuous quality checks, and a production deployment pipeline. Core '
    'features - WYSIWYG editing, true pagination, headers and footers, offline autosave, and PDF, '
    'DOCX, HTML, and JSON export - are operational today.', body))
story.append(Paragraph(
    'The development roadmap prioritizes: (1) advanced typography controls such as word and letter '
    'spacing, paragraph gaps, indents, and drop caps tuned for Bengali conjuncts; (2) refinements of '
    'the Farma imposition engine to cover every signature format used by Bangladeshi presses; '
    '(3) per-page header and footer overrides for professional front matter; (4) clickable hyperlinks '
    'inside exported PDFs; and (5) a professional template library for common book genres. Each step '
    'moves the platform closer to a complete, free publishing suite for Bangladesh.', body))

# Closing line
story.append(Spacer(1, 10))
closing = Paragraph(
    '<i>Submitted by Topu Biswas, B.Sc. (Engg.) 2nd Year, Department of Information and Communication '
    'Engineering (ICE), University of Rajshahi.</i>',
    ParagraphStyle(name='Close', fontName='FreeSerif', fontSize=9.5, leading=14,
                   textColor=TEXT_MUTED, alignment=TA_LEFT))
story.append(HRFlowable(width='100%', thickness=0.6, color=BORDER, spaceBefore=6, spaceAfter=8))
story.append(closing)

doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
print(f'BODY OK: {OUT}')
